version: '3'
services:
  mariadb:
    image: deniskasak/uni-nao:mariadb
    restart: always
    #ports:
    #  - "3306:3306"

  transcriber:
    image: deniskasak/uni-nao:transcriber
    restart: always
    #ports:
    #  - "5002:5000"
    environment:
      WHISPER_MODEL: base

  webserver:
    image: deniskasak/uni-nao:webserver
    restart: always
    depends_on:
      - transcriber
    ports:
      - "5001:5000"
    environment:
      TRANSCRIBER_HOST: transcriber
      TRANSCRIBER_PORT: 5000
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: nao
      DB_DATABASE: nao
