version: '3'
services:
  mariadb:
    image: deniskasak/uni-nao:mariadb
    restart: always
    environment:
      - MYSQL_ROOT_USERNAME=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 3306:3306